"""Stuff for storing rounds and submissions in a generic way. I should think of a better name at some point, and also document the format outside of just source code comments (even if it's just autogenerated)"""

from .classes import Round, ScoringOptions, Season, Submission, TPGType
from .combine import combine_player_submissions
from .io import get_main_tpg_rounds_with_path, load_rounds, load_rounds_async, rounds_to_json
from .main_tpg_import import get_main_tpg_rounds
from .per_user import (
	get_main_tpg_submissions_per_user,
	get_submissions_per_user,
	get_submissions_per_user_from_path,
	get_submissions_per_user_with_path,
)
from .tracker_import import convert_submission_tracker

__all__ = [
	'Round',
	'ScoringOptions',
	'Season',
	'Submission',
	'TPGType',
	'combine_player_submissions',
	'convert_submission_tracker',
	'get_main_tpg_rounds',
	'get_main_tpg_rounds_with_path',
	'get_main_tpg_submissions_per_user',
	'get_submissions_per_user',
	'get_submissions_per_user_from_path',
	'get_submissions_per_user_with_path',
	'load_rounds',
	'load_rounds_async',
	'rounds_to_json',
]
