"""Stuff for storing rounds and submissions in a generic way. I should think of a better name at some point, and also document the format outside of just source code comments (even if it's just autogenerated)"""

from .classes import PlayerName, PlayerUsername, Round, ScoringOptions, Season, Submission, TPGType
from .combine import combine_player_submissions_to_point_sets
from .io import get_main_tpg_rounds_with_path, load_rounds, load_rounds_async, rounds_to_json
from .main_tpg_import import get_main_tpg_rounds, get_player_display_names, get_player_username
from .tracker_import import convert_submission_tracker

__all__ = [
	'PlayerName',
	'PlayerUsername',
	'Round',
	'ScoringOptions',
	'Season',
	'Submission',
	'TPGType',
	'combine_player_submissions_to_point_sets',
	'convert_submission_tracker',
	'get_main_tpg_rounds',
	'get_main_tpg_rounds_with_path',
	'get_player_display_names',
	'get_player_username',
	'load_rounds',
	'load_rounds_async',
	'rounds_to_json',
]
